using System;
using System.Collections.Generic;

namespace BISM.Models.BalimoonBML
{
    public partial class PostransactionLine
    {
        public int PostransactionLineId { get; set; }
        public int PostransactionHeaderId { get; set; }
        public string ReceiptNo { get; set; }
        public int SeqLineNo { get; set; }
        public int EntryType { get; set; }
        public string BarcodeNo { get; set; }
        public string Number { get; set; }
        public int EntryStatus { get; set; }
        public string CurrencyCode { get; set; }
        public string VariantCode { get; set; }
        public string Description { get; set; }
        public string UnitofMeasure { get; set; }
        public string StoreNo { get; set; }
        public string PosterminalNo { get; set; }
        public string SalesStaff { get; set; }
        public int TextType { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ProductGroupCode { get; set; }
        public decimal Price { get; set; }
        public decimal NetPrice { get; set; }
        public decimal Quantity { get; set; }
        public string PriceGroupCode { get; set; }
        public string Vatcode { get; set; }
        public decimal Vatpercent { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal CostAmount { get; set; }
        public decimal CostPrice { get; set; }
        public decimal NetAmount { get; set; }
        public decimal Vatamount { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountInCurrency { get; set; }
        public string CardType { get; set; }
        public string CardCustomerCoupItemNo { get; set; }
        public string VatBusPostingGroup { get; set; }
        public string VatProdPostingGroup { get; set; }
        public string ItemDiscGroup { get; set; }
        public byte SystemBlockManualDiscount { get; set; }
        public int CardEntryNo { get; set; }
        public string CouponEanorg { get; set; }
        public byte ItemNumberScanned { get; set; }
        public byte PriceinBarcode { get; set; }
        public byte PriceChange { get; set; }
        public byte WeightmanuallyEntered { get; set; }
        public byte ScaleItem { get; set; }
        public byte QuantityinBarcode { get; set; }
        public int DispensePrinting { get; set; }
        public byte LinkedNonotOrig { get; set; }
        public byte OrigofaLinkedItemList { get; set; }
        public byte PriceOverride { get; set; }
        public byte ItemDeptNegative { get; set; }
        public byte CountasOne { get; set; }
        public string ItemPostingGroup { get; set; }
        public decimal TotalRoundedAmt { get; set; }
        public decimal OrgPriceIncVat { get; set; }
        public decimal OrgPriceExcVat { get; set; }
        public string SerialNo { get; set; }
        public string LotNo { get; set; }
        public DateTime ExpirationDate { get; set; }
        public byte OfferBlockedPoints { get; set; }
        public string OrigfromInfocode { get; set; }
        public string OrigfromSubcode { get; set; }
        public int InfocodeEntryLineNo { get; set; }
        public decimal InfocodeSelectedQty { get; set; }
        public int ShiftedfromLineNo { get; set; }
        public decimal SplitfromLineNoQty { get; set; }
        public int SplitfromLineNo { get; set; }
        public int DiscInfoLineNo { get; set; }
        public byte DiscountTriggered { get; set; }
        public decimal QuantityDiscounted { get; set; }
        public byte InfoCodeDiscDisable { get; set; }
        public decimal InfoCodeDiscPercent { get; set; }
        public decimal PeriodicDiscPercent { get; set; }
        public string PromotionNo { get; set; }
        public int MixandMatchLineNo { get; set; }
        public decimal LineDiscPercent { get; set; }
        public decimal TotalDiscPercent { get; set; }
        public int TotDiscInfoLineNo { get; set; }
        public decimal TotalDiscAmount { get; set; }
        public decimal PeriodicDiscountAmount { get; set; }
        public byte DealLine { get; set; }
        public int DealModifierLineNo { get; set; }
        public int DealLineNo { get; set; }
        public byte PromptedforIpo { get; set; }
        public decimal CustomerPrice { get; set; }
        public int ItemPointOfferMemberPoints { get; set; }
        public decimal CustomerDiscPercent { get; set; }
        public decimal CustomerQtyUsed { get; set; }
        public decimal CouponQtyUsed { get; set; }
        public decimal CouponDiscountAmount { get; set; }
        public string ParentTransactionDocNo { get; set; }
        public int ParentLine { get; set; }
        public int RoundNo { get; set; }
        public int GuestSeatNo { get; set; }
        public byte Marked { get; set; }
        public int GroupMarking { get; set; }
        public int ParentCompression { get; set; }
        public int JournalCompression { get; set; }
        public int SplitOriginLineNo { get; set; }
        public int ViewLineinJournal { get; set; }
        public byte SystemExcludefromOffers { get; set; }
        public byte SystemUnchangableQuantity { get; set; }
        public byte SystemUnchangablePrice { get; set; }
        public byte SystemUnchangableDiscounts { get; set; }
        public byte SystemExcludefromVoid { get; set; }
        public byte SystemUnchangableOffer { get; set; }
        public byte SystemExcludefromRefund { get; set; }
        public byte SystemBlockPromotionPrice { get; set; }
        public decimal PrepaymentPercent { get; set; }
        public decimal PrepmtLineAmount { get; set; }
        public byte PrepaymentLine { get; set; }
        public byte PrepaymentVoided { get; set; }
        public int CouponFunction { get; set; }
        public string CouponCode { get; set; }
        public decimal CouponAmount { get; set; }
        public decimal CouponDiscountPercent { get; set; }
        public byte ValidinTransaction { get; set; }
        public int NoofCouponstoPrint { get; set; }
        public byte AutomaticallyCreated { get; set; }
        public string CouponBarcodeNo { get; set; }
        public DateTime FirstValidDate { get; set; }
        public DateTime LastValidDate { get; set; }
        public string CreatedorUsedbyOfferNo { get; set; }
        public int CouponLinkedtoLineNo { get; set; }
        public decimal DiscountAmtforPrinting { get; set; }
        public decimal CouponAmtForPrinting { get; set; }
        public string SalesType { get; set; }
        public string RestaurantMenuTypeCode { get; set; }
        public int RestaurantMenuType { get; set; }
        public int ExcludedBomLineNo { get; set; }
        public byte ExcludedBomItem { get; set; }
        public decimal OrgPriceBeforeRounding { get; set; }
        public decimal DealAddedAmount { get; set; }
        public decimal DealModifierAddedAmt { get; set; }
        public string ParentItemNo { get; set; }
        public string OrigTransactionStore { get; set; }
        public string OrigTransactionPos { get; set; }
        public int OrigTransactionNo { get; set; }
        public int OrigTransactionLineNo { get; set; }
        public decimal RemainingQuantity { get; set; }
        public int OrigPerDiscType { get; set; }
        public string OrigPerDiscGroup { get; set; }
        public byte BenefitItem { get; set; }
        public byte Fuelitem { get; set; }
        public byte RetailSpecialOrder { get; set; }
        public int DeliveringMethod { get; set; }
        public int VendorDeliversto { get; set; }
        public int Sourcing { get; set; }
        public int Deliverfrom { get; set; }
        public string DeliveryLocationCode { get; set; }
        public decimal SetLimitAmount { get; set; }
        public decimal SpoprepaymentPercent { get; set; }
        public decimal PaymentActual { get; set; }
        public int WhseProcess { get; set; }
        public int Status { get; set; }
        public int DeliveryStatus { get; set; }
        public string ConfigurationId { get; set; }
        public byte MandatoryOptionsExist { get; set; }
        public int AddChargeOption { get; set; }
        public string DeliveryReferenceNo { get; set; }
        public string DeliveryUserId { get; set; }
        public DateTime DeliveryDateTime { get; set; }
        public decimal Counter { get; set; }
        public string OptionValueText { get; set; }
        public DateTime EstimatedDeliveryDate { get; set; }
        public DateTime NolaterthanDate { get; set; }
        public decimal PaymentAtOrderEntryLimit { get; set; }
        public decimal PaymentAtDeliveryLimit { get; set; }
        public int ReturnPolicy { get; set; }
        public decimal NonRefundAmount { get; set; }
        public int SourcingStatus { get; set; }
        public decimal PaymentAtPurchaseOrderLimit { get; set; }
        public int SpodocumentMethod { get; set; }
        public string StoreSalesLocation { get; set; }
        public string SpowhseLocation { get; set; }
        public string VendorNo { get; set; }
        public string AdditionalChargeCode { get; set; }
        public byte IncludeInParentLine { get; set; }
        public byte AddChargeExists { get; set; }
        public string PaymentProfileCode { get; set; }
        public int CancelPermitted { get; set; }
        public int AddChrgLinkedtoLine { get; set; }
        public short RowStatus { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedTime { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime? LastModifiedTime { get; set; }
    }
}
